### ISSUE TITLE
Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}

### ISSUE THREAD

**Issue by andirosu** [mobilpay/magento2#1]
Magento v2.3.2

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file app/code/Netopia/Netcard/etc/adminhtml/system.xml" is invalid:
Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 81

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 81

Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 87

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 87

Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 93

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 93

Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 99

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 99

Verify the XML and try again.

**Comment by navid59** [comment]
Hello @andirosu 
The Module is tested by Magento 2.4 & 2.3 in different servers
We haven't such problems.

May you have diff specific configuration on your server.
 
Please try the on of the following test:
#1) in app/code/Netopia/Netcard/etc/adminhtml/system.xml on the lines what you have problem, there is an empty tag `<upload_dir></upload_dir>`
please replace the `<upload_dir></upload_dir>` to `<upload_dir />`

Then do setup upgrade or setup compile then clean the cache as well

#2) if test #1 didn't work for you try to address the Certificate Directory Path in this lines.

**Comment by tiberiucontiu** [comment]
Hello @navid59 

I have the very same problem as @andirosu. If you look at this file vendor/magento/module-config/etc/system_file.xsd where all the xml definition resides you will see this:

![image](https://user-images.githubusercontent.com/2530506/110661297-17a68580-81cd-11eb-834a-64216b782d53.png)

In the same file, if you search by 'upload_dir' keyword, you will see that upload_dir element is defined of type="typeUploadDir". Don't know how you test, but it cannot work with <upload_dir></upload_dir> or <upload_dir /> syntax.

![image](https://user-images.githubusercontent.com/2530506/110661666-7b30b300-81cd-11eb-86c9-dd58ddb1d71f.png)

So please accept @andirosu pull request.

**Comment by navid59** [comment]
Hello , 
First Thank you for share your idea with us.

Infact , is not necessary the UploadDir tag any more .
We just had some other upgrade also.

Let me few day's to get feedback from Testing Dept .
We will update the Git repository ASAP.

Regards
